export const config = {
  highlight: false,
  isAsync: true,
  listName: "Set Event 3D Attributes",
  displayText:
    "Set event [i]{0}[/i] with tag [i]{1}[/i] 3D attributes: position: ([i]{2}[/i], [i]{3}[/i], [i]{4}[/i]), velocity: ([i]{5}[/i], [i]{6}[/i], [i]{7}[/i]), forward: ([i]{8}[/i], [i]{9}[/i], [i]{10}[/i]), up: ([i]{11}[/i], [i]{12}[/i], [i]{13}[/i])",
  description: "Set the 3D attributes of the specified FMOD event.",
  params: [
    {
      id: "name",
      name: "Name",
      desc: "",
      type: "string",
      initialValue: "",
    },
    {
      id: "tag",
      name: "Tag",
      desc: "",
      type: "string",
      initialValue: "",
    },
    {
      id: "x",
      name: "X",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "y",
      name: "Y",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "z",
      name: "Z",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "velocity-x",
      name: "Velocity X",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "velocity-y",
      name: "Velocity Y",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "velocity-z",
      name: "Velocity Z",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "forward-x",
      name: "Forward X",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "forward-y",
      name: "Forward Y",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "forward-z",
      name: "Forward Z",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "up-x",
      name: "Up X",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "up-y",
      name: "Up Y",
      desc: "",
      type: "number",
      initialValue: "0",
    },
    {
      id: "up-z",
      name: "Up Z",
      desc: "",
      type: "number",
      initialValue: "0",
    },
  ],
};

export const expose = true;

export default async function (
  name,
  tag,
  x,
  y,
  z,
  vx,
  vy,
  vz,
  fx,
  fy,
  fz,
  ux,
  uy,
  uz
) {
  if (!this.curInst) return;
  await this.curInst.SendMessageAsync("set-event-3d-attributes", [
    name,
    tag,
    x,
    y,
    z,
    vx,
    vy,
    vz,
    fx,
    fy,
    fz,
    ux,
    uy,
    uz,
  ]);
}
